# -*- coding: utf-8 -*-
"""FantasyFootballScorePredictorQB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dr2mR7bF4sXU_D23DXbmEVcwCdoBcZZr
"""

import pandas as pd

df_pass = pd.read_csv("ScorePredictorPassYds.csv")
df_pass.head(50)

df_pass.size

df_rush_qb = pd.read_csv("ScorePredictorRushYdsQB.csv")
df_rush_qb.head(30)

df_merged = pd.merge(df_pass, df_rush_qb, left_on="Player", right_on="Player", how="inner")
df_merged.head(50)

df_merged["PassAtt"] = df_merged["Att_x"]
df_merged["RushAtt"] = df_merged["Att_y"]
df_merged["PassYds"] = df_merged["Yds_x"]
df_merged["PassTD"] = df_merged["TD_x"]
df_merged["RushYds"] = df_merged["Yds_y"]
df_merged["RushTD"] = df_merged["TD_y"]
df_merged["PassY/A"] = df_merged["Y/A_x"]
df_merged["RushY/A"] = df_merged["Y/A_y"]

df_merged = df_merged[["Player", "Team", "G", "Cmp", "PassAtt", "PassYds", "PassTD", "Int", "PassY/A", "PassRtg", "QBR", "RushAtt", "RushYds", "RushTD", "RushY/A", "Y/G"]]
df_merged.head(50)

df_merged = df_merged.dropna()
df_merged.head(50)

total_fpts = (df_merged['PassYds'].astype("int")/25 + df_merged['PassTD'].astype("int") * 4 + df_merged['Int'].astype("int") * -2 + df_merged['RushYds'].astype("int")/10 + df_merged['RushTD'].astype("int") * 6)

fpts_g = total_fpts / df_merged['G'].astype("int")
fpts_g.round(2)

df_merged["FPTS/G"] = fpts_g
df_merged.head(50)

df_pass_yds_allowed = pd.read_csv("PassYdsAllowed.csv")
df_pass_yds_allowed.head(32)

qb_name = input("Enter QB Name:\n")

qb_opponent = input(f"Who is {qb_name} playing against?\n")

opponent_rtg = (df_pass_yds_allowed[df_pass_yds_allowed['Team'] == qb_opponent]['RTG'])
opponent_rtg

rtg_mult = (opponent_rtg/90)**2
rtg_mult

fpts_g = float((df_merged[df_merged['Player'] == qb_name]['FPTS/G']))
fpts_g

fpts_g = float(fpts_g * rtg_mult)
fpts_g

injury = input(f"Does {qb_name} have an injury? (Y/N) ")
if injury == "Y":
  injury_type = input(f"""\nSelect {qb_name}'s injury status:
  P - Probable
  Q - Questionable
  D - Doubtful
  O - Out\n""")
  if injury_type == "O":
    fpts_g_round = fpts_g * 0
    print(f"Projected Fantasy Points: {round(fpts_g_round, 2)}")
  elif injury_type == "Q":
    fpts_g_round = fpts_g * 0.8
    print(f"Projected Fantasy Points: {round(fpts_g_round, 2)}")
  elif injury_type == "D":
    fpts_g_round = fpts_g * 0
    print(f"Projected Fantasy Points: {round(fpts_g_round, 2)}")
  elif injury_type == "P":
    fpts_g_round = fpts_g
    print(f"Projected Fantasy Points: {round(fpts_g_round, 2)}")
elif injury == "N":
    fpts_g_round = fpts_g
    print(f"Projected Fantasy Points: {round(fpts_g_round, 2)}")
