# -*- coding: utf-8 -*-
"""FantasyFootballScorePredictorRB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZn5a_OT_at9qxBuyiYQewRxgpb5mvGb
"""

import pandas as pd

df_rush = pd.read_csv("ScorePredictorRushYds.csv")
df_rush.head(50)

df_rec_rb = pd.read_csv("ScorePredictorRecYdsRB.csv")
df_rec_rb.head(50)

df_merged = pd.merge(df_rush, df_rec_rb, left_on="Player", right_on="Player", how="inner")
df_merged.head(50)

df_merged["Team"] = df_merged["Team_x"]
df_merged["RushYds"] = df_merged["Yds_x"]
df_merged["RushTD"] = df_merged["TD_x"]
df_merged["RecYds"] = df_merged["Yds_y"]
df_merged["RecTD"] = df_merged["TD_y"]

df_merged[["Player", "Team", "G", "Att", "RushYds", "RushTD", "AVG", "Tgt",	"Rec",	"RecYds",	"RecTD"]]

df_rush.head(100)

df_rec_rb = pd.read_csv("ScorePredictorRecYdsRB.csv")
df_rec_rb.head(50)

df_merged = pd.merge(df_rush, df_rec_rb, left_on="Player", right_on="Player", how="inner")
df_merged.head(100)

df_merged["Team"] = df_merged["Team_x"]
df_merged["RushYds"] = df_merged["Yds_x"]
df_merged["RushTD"] = df_merged["TD_x"]
df_merged["RecYds"] = df_merged["Yds_y"]
df_merged["RecTD"] = df_merged["TD_y"]
df_merged[["Player", "Team", "G", "Att", "RushYds", "RushTD", "AVG", "Tgt",	"Rec",	"RecYds",	"RecTD"]]

total_fpts = (df_merged['RushYds'].astype("int")/10 + df_merged['RushTD'].astype("int") * 6 + df_merged['Rec'].astype("int") * 1 + df_merged['RecYds'].astype("int")/10 + df_merged['RecTD'].astype("int") * 6)
total_fpts

fpts_g = total_fpts / df_merged['G'].astype("int")
fpts_g.round(2)

df_merged["FPTS/G"] = fpts_g
df_merged.head(50)

df_yds_allowed = pd.read_csv("RushYdsAllowed.csv")
df_yds_allowed.head(32)

opponent_rush_yds = df_yds_allowed['Rush Yds']
opponent_rush_yds

opponent_rush_tds = df_yds_allowed['TD']
opponent_rush_tds

fpts_g_allowed = ((opponent_rush_yds / 10) + (opponent_rush_tds * 6))/17
df_yds_allowed["FPTS/G"] = fpts_g_allowed
df_yds_allowed.head(32)

rb_name = input("Enter RB name: \n")

rb_opponent = input(f"Who is {rb_name} playing against? \n")

opponent_fpts_g = (df_yds_allowed[df_yds_allowed['Team'] == rb_opponent]['FPTS/G'])
opponent_fpts_g

rush_mult = (opponent_fpts_g/16)**0.5
rush_mult

avg_fpts = float((df_merged[df_merged['Player'] == rb_name]['FPTS/G']))
avg_fpts

rb_fpts = float(avg_fpts * rush_mult)
rb_fpts

injury = input(f"Does {rb_name} have an injury? (Y/N) ")
if injury == "Y":
  injury_type = input(f"""\nSelect {rb_name}'s injury status:
  P - Probable
  Q - Questionable
  D - Doubtful
  O - Out\n""")
  if injury_type == "O":
    rb_fpts_round = rb_fpts * 0
    print(f"Projected Fantasy Points: {round(rb_fpts_round, 2)}")
  elif injury_type == "Q":
    rb_fpts_round = rb_fpts * 0.8
    print(f"Projected Fantasy Points: {round(rb_fpts_round, 2)}")
  elif injury_type == "D":
    rb_fpts_round = rb_fpts * 0
    print(f"Projected Fantasy Points: {round(rb_fpts_round, 2)}")
  elif injury_type == "P":
    rb_fpts_round = rb_fpts
    print(f"Projected Fantasy Points: {round(rb_fpts_round, 2)}")
elif injury == "N":
    print(f"Projected Fantasy Points: {round(rb_fpts, 2)}")
