# -*- coding: utf-8 -*-
"""FantasyFootballScorePredictorWR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pddWk7exCo9h4VsDp7YpJMO-52JKkhL3
"""

import pandas as pd

"""fantasy score calculator"""

# use input to get an input for each stat --> multiply input by # pts/stat

df_rec = pd.read_csv("ScorePredictorRecYds.csv")
print(df_rec)

df_rec['Name'].str[-3:]

df_rec['Name'].str[-6:]

df_rec['Name'].str[-3:].str.isupper()

df_rec['Name'].str[-3:].str.isupper().head(10)

df_rec[df_rec['Name'].str[-3:].str.isupper() == False]

df_rec[df_rec['Name'].str[-3:].str.isupper() == False]['Name']

df_rec[df_rec['Name'].str[-3:].str.isupper() == False]['Name'].str[-2:]



in_progress = df_rec[df_rec['Name'].str[-3:].str.isupper() == True]
in_progress.head(20)

in_progress[in_progress['Name'].str[-4:].str.isupper() == False]

in_progress = in_progress[in_progress['Name'].str[-4:].str.isupper() == True]
in_progress.head(20)

in_progress['Name'].str[-4]=="."

in_progress = in_progress[df_rec['Name'].str[-5:].str.isupper() == True]
in_progress.head(20)

in_progress = in_progress[df_rec['Name'].str[-6:].str.isupper() == True]
in_progress.head(20)

def lowercase_at_index(column_values, index):
  return column_values.str[index].str.isupper() == False

unsorted_df = df_rec.copy()
unsorted_df.head(10)

unsorted_df['Team'].isna().head(10)

lowercase_at_index(unsorted_df['Name'], -3).head(10)

mask = lowercase_at_index(unsorted_df['Name'], -3) & unsorted_df['Team'].isna()
mask.head(10)

two_letter_team_names = unsorted_df[mask]
two_letter_team_names.head()

unsorted_df = unsorted_df[~mask]
unsorted_df.head()

def lowercase_at_index(player_names, index):
  return player_names.str[index].str.isupper() == False

def team_starts_at(player_names, current_team, index):
  return lowercase_at_index(player_names, index-1) & current_team.isna()

unsorted_df = df_rec.copy()
unsorted_df['Team'] = unsorted_df['Team'].astype('string')
unsorted_df.head()

# in order to know if a players team starts at some given index
# two things must be true: the index before it should be lowercase
# and also, they shouldn't already have a team
# this prevents duplication when looking for 3 letter team names
# as a players last name 4 letters from the end would still be lowercase
# eg: SmithLV has lowercase both at -3 and -4
# but once their team is assigned, they will not be checked for lowercase at -4
mask = team_starts_at(unsorted_df['Name'], unsorted_df['Team'], -2)
unsorted_df.loc[mask, 'Team'] = unsorted_df.loc[mask, 'Name'].str[-2:]
unsorted_df.loc[mask, 'Name'] = unsorted_df.loc[mask, 'Name'].str[:-2]
unsorted_df.head(10)

unsorted_df[~unsorted_df['Team'].isna()]

mask = team_starts_at(unsorted_df['Name'], unsorted_df['Team'], -3)
unsorted_df.loc[mask, 'Team'] = unsorted_df.loc[mask, 'Name'].str[-3:]
unsorted_df.loc[mask, 'Name'] = unsorted_df.loc[mask, 'Name'].str[:-3]
unsorted_df.head(10)

mask = unsorted_df['Team'].isna()
unsorted_df.loc[mask, 'Team'] = unsorted_df.loc[mask, 'Name'].str[-3:]
unsorted_df.loc[mask, 'Name'] = unsorted_df.loc[mask, 'Name'].str[:-3]
unsorted_df.head(10)

unsorted_df[unsorted_df['Team'].isna()]

unsorted_df.head(20)

#find each player's total fpts and divide by games played

unsorted_df['YDS'].str.replace(",", "").astype("int")

total_fpts = (unsorted_df['YDS'].str.replace(",", "").astype("int"))/10 + (unsorted_df['TD'].astype("int"))*6 + unsorted_df['REC'].astype("int")

total_fpts.head(10)

fpts_per_game = total_fpts/(unsorted_df['GP'])
fpts_per_game.head(20)

unsorted_df["FPTS/G"] = total_fpts/(unsorted_df['GP'])
unsorted_df.head(10)

df_yds_allowed = pd.read_csv("PassYdsAllowed.csv")
df_yds_allowed.head(20)

wr_name = input("Enter WR Name:\n")

wr_opponent = input(f"Who is {wr_name} playing against?\n")

opponent_rtg = (df_yds_allowed[df_yds_allowed['Team'] == wr_opponent]['RTG'])
opponent_rtg

# (unsorted_df[unsorted_df['Name'] == wr_name]['FPTS/G'])
rtg_mult = (opponent_rtg/90)**2
rtg_mult

avg_fpts = float((unsorted_df[unsorted_df['Name'] == wr_name]['FPTS/G']))
avg_fpts

avg_fpts = float(avg_fpts * rtg_mult)
avg_fpts

injury = input(f"Does {wr_name} have an injury? (Y/N) ")
if injury == "Y":
  injury_type = input(f"""\nSelect {wr_name}'s injury status:
  P - Probable
  Q - Questionable
  D - Doubtful
  O - Out\n""")
  if injury_type == "O":
    avg_fpts_round = avg_fpts * 0
    print(f"Projected Fantasy Points: {round(avg_fpts_round, 2)}")
  elif injury_type == "Q":
    avg_fpts_round = avg_fpts * 0.8
    print(f"Projected Fantasy Points: {round(avg_fpts_round, 2)}")
  elif injury_type == "D":
    avg_fpts_round = avg_fpts * 0
    print(f"Projected Fantasy Points: {round(avg_fpts_round, 2)}")
  elif injury_type == "P":
    avg_fpts_round = avg_fpts
    print(f"Projected Fantasy Points: {round(avg_fpts_round, 2)}")
elif injury == "N":
    avg_fpts_round = avg_fpts
    print(f"Projected Fantasy Points: {round(avg_fpts_round, 2)}")
